# Generated by Django 5.0.4 on 2024-11-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название карты')),
                ('description', models.TextField(blank=True, verbose_name='Описание карты')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('modes', models.CharField(max_length=255, verbose_name='Режимы')),
                ('players', models.IntegerField(max_length=255, verbose_name='Максимум игроков')),
                ('file', models.FileField(upload_to='map_design/template', verbose_name='Шаблон карты')),
                ('art', models.FileField(upload_to='map_design/art', verbose_name='Арт')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Шаблоны карт',
                'verbose_name_plural': 'Шаблоны карт',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
