# Generated by Django 5.0.4 on 2024-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('img', models.FileField(upload_to='objects/portrait', verbose_name='Портрет')),
                ('side', models.CharField(max_length=50, verbose_name='Фракция')),
                ('displayName', models.CharField(max_length=255, verbose_name='Отображаемое имя')),
                ('buildCost', models.IntegerField(verbose_name='Стоимость')),
                ('kindOf', models.TextField(blank=True, verbose_name='Разновидность')),
            ],
            options={
                'verbose_name': 'Игровые объекты',
                'verbose_name_plural': 'Игровые объекты',
                'ordering': ['side'],
            },
        ),
        migrations.AlterField(
            model_name='maptemplates',
            name='players',
            field=models.IntegerField(verbose_name='Максимум игроков'),
        ),
    ]
