# Generated by Django 5.0.4 on 2024-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_gameobjects_alter_maptemplates_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptemplates',
            name='data',
            field=models.TextField(blank=True, verbose_name='Технические данные'),
        ),
        migrations.AddField(
            model_name='maptemplates',
            name='img',
            field=models.FileField(blank=True, upload_to='map_design/img', verbose_name='Изображение'),
        ),
    ]
