# Generated by Django 5.0.4 on 2024-12-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_maptemplates_data_maptemplates_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maptemplates',
            name='img',
            field=models.FileField(upload_to='map_design/img', verbose_name='Изображение'),
        ),
    ]
