# Generated by Django 5.0.4 on 2024-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mode_alter_news_options_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание карты в игре'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание карты на сайте'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
