# Generated by Django 5.0.4 on 2024-12-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_maps_description_alter_maps_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
