# Generated by Django 5.0.4 on 2024-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='file',
        ),
        migrations.AddField(
            model_name='maps',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='maps',
            name='template',
            field=models.CharField(blank=True, max_length=255, verbose_name='Шаблон карты'),
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
